### PR TITLE
Initialize nvidia-drm on kernel-5.11

### PR DESCRIPTION
**Pull request by wojnilowicz**
Makes /dev/dri/card0 appear again and enables sddm to show greeter.

### CODE REVIEW

**Comment by kwizart** [comment]
I think this is the good way forward.
Best way to verify the code is to check how it is done with the 390xx or later series...

**Comment by wojnilowicz** [comment]
> I think this is the good way forward.
> Best way to verify the code is to check how it is done with the 390xx or later series...

I did so. 390xx is way ahead of 340xx, so not much can be taken from it.

**Comment by kwizart** [comment]
@wojnilowicz can you go ahead with this ? (or what is holding the PR ?)

**Comment by wojnilowicz** [comment]
> @wojnilowicz can you go ahead with this ? (or what is holding the PR ?)

Firstly, I have no commit rights. Secondly, I'm aware that this patch is not a proper one, so maybe someone with more complex hardware configuration than mine could check if it works for him as well.

**Comment by kwizart** [comment]
I think you should have commit rights, so if you have a rpmfusion FAS account, you can request the rights on admin.rpmfusion.org/pkgdb

> I'm aware that this patch is not a proper one 
Why that ? If it works for you I think it worth having in testing for others. Maybe you can submit a koji scratch build.

**Comment by wojnilowicz** [comment]
> I think you should have commit rights, so if you have a rpmfusion FAS account, you can request the rights on admin.rpmfusion.org/pkgdb

Ok, I'll request the rights.

> > I'm aware that this patch is not a proper one
> > Why that ? If it works for you I think it worth having in testing for others. Maybe you can submit a koji scratch build.

The wrong thing was that I put a part of the code, that was executed before, out of an execution route.
In the new patch:
1) I used the code from nvidia 390.143 so I could remove a lot of code imported from drm_legacy_pci_{init,exit}, but still I don't know how to test if the code works as intended. 
2) I replaced most of the defines like "#if LINUX_VERSION_CODE <= KERNEL_VERSION(5, 10, 0)" with proper defines from conftest.sh (updated to 390.143), so hopefuly it will be better at avoiding bugs like at https://bugzilla.rpmfusion.org/show_bug.cgi?id=6004

I tesed it with kernel-5.10 and 5.11.

I will try to investigate what a koji scratch build is and maybe prepare one.

**Comment by wojnilowicz** [comment]
> I think you should have commit rights, so if you have a rpmfusion FAS account, you can request the rights on admin.rpmfusion.org/pkgdb

I don't want to give my telephone number to register a rpmfusion FAS account, so please merge my PR if you would like to do so.

**Comment by kwizart** [comment]
Well, there is no need for a phone number. If really needed (it would be a bug), put a fake one.

**Comment by wojnilowicz** [comment]
> Well, there is no need for a phone number. If really needed (it would be a bug), put a fake one.

Ok, I applied for the packagers group and awaiting approval.

**Comment by leigh123linux** [comment]
> > Well, there is no need for a phone number. If really needed (it would be a bug), put a fake one.
> 
> Ok, I applied for the packagers group and awaiting approval.

Approved.

**Comment by leigh123linux** [comment]
@wojnilowicz Are you aware that github is just a mirror for https://pkgs.rpmfusion.org/cgit/nonfree/nvidia-340xx-kmod.git/
nothing here gets merged.

**Comment by wojnilowicz** [comment]
> @wojnilowicz Are you aware that github is just a mirror for https://pkgs.rpmfusion.org/cgit/nonfree/nvidia-340xx-kmod.git/
> nothing here gets merged.

No, I wasn't aware. Thanks for the hint. Nevertheless, I believe that I still wouldn't have commit rights at cgit as seen at
https://admin.rpmfusion.org/pkgdb/package/nonfree/nvidia-340xx-kmod/
and additionally no one beside me tested usefulnes of this patch.

**Comment by kwizart** [comment]
@wojnilowicz I would approve anyway this change. Given you have tested it, you have done the work expected from a maintainer.
If you have any regression, thoses will be investigated at your own pace. People had time to give feedback.

Please don't be shy you have done an excellent job.

**Comment by wojnilowicz** [comment]
> @wojnilowicz I would approve anyway this change. Given you have tested it, you have done the work expected from a maintainer.
> If you have any regression, thoses will be investigated at your own pace. People had time to give feedback.
> 
> Please don't be shy you have done an excellent job.

Thanks. How should I proceed with commiting this PR?

**Comment by thosoo** [comment]
I have tested your patch and it worked great, @wojnilowicz .
However, I have changed it a little by putting all into a single file (kernel-5.11.patch), because of cluttering.
You have made great work! Thanks.

I have committed the changes on the rpmfusion git.

**Comment by wojnilowicz** [comment]
Already merged.

**Pull request closed without merging**
